schema: src/graphql/**/*.graphqls
schemaEntrypoint: src/graphql/__generated__/schema.graphqls
documents: src/graphql/**/*.graphql
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  enumValues:
    Language: '@prisma/client#Language'
  enumPrefix: GQL

cacheDir: __codegen_cache__
