schema: src/graphql/**/*.graphqls
documents: src/graphql/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
config:
  enumValues:
    Language: '@prisma/client#Language'
  enumPrefix: GQL
cacheDir: .cache/graphql-let
