services:
  web:
    build: .
    command: /bin/sh -c 'npx prisma migrate deploy --preview-feature && npx prisma db seed --preview-feature && npm run build && npm start'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
