services:
  web:
    command: /bin/sh -c 'npx prisma migrate deploy --preview-feature && npx prisma db seed --preview-feature && npm run dev'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.local
      - src/prisma/.env.local
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.2-alpine
    env_file:
      - src/prisma/.env.local
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  data: