-- CreateEnum
CREATE TYPE "enum_Pack_language" AS ENUM ('python', 'javascript', 'typescript', 'csharp', 'elixir', 'other');

-- CreateEnum
CREATE TYPE "enum_User_type" AS ENUM ('user', 'admin');

-- CreateTable
CREATE TABLE "snippet" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "pack_id" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pack" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "language" "enum_Pack_language" NOT NULL DEFAULT E'other',
    "upvotes" INTEGER NOT NULL DEFAULT 0,
    "author_id" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "github_id" INTEGER NOT NULL,
    "username" VARCHAR(39) NOT NULL,
    "type" "enum_User_type" NOT NULL DEFAULT E'user',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user.github_id_unique" ON "user"("github_id");

-- CreateIndex
CREATE UNIQUE INDEX "user.username_unique" ON "user"("username");

-- AddForeignKey
ALTER TABLE "snippet" ADD FOREIGN KEY ("pack_id") REFERENCES "pack"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pack" ADD FOREIGN KEY ("author_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
