services:
  db:
    image: postgres:14.0-alpine
    env_file: ../src/prisma/.env.local
    container_name: snippethub_prod_db
  web:
    container_name: snippethub_prod_web
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/sh -c 'npx prisma migrate deploy && npm run prisma:seed && npm run build && npm start -- -p 8080'
    ports:
      - 8080:8080
    env_file:
      - ../.env.local
      - ../src/prisma/.env.local
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:8080
