-- CreateEnum
CREATE TYPE "enum_Snippet_language" AS ENUM ('python', 'javascript', 'typescript', 'csharp', 'elixir');

-- CreateEnum
CREATE TYPE "enum_User_type" AS ENUM ('user', 'admin');

-- CreateTable
CREATE TABLE "Snippet" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "authorId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "language" "enum_Snippet_language",
    "upvotes" INTEGER NOT NULL DEFAULT 0,
    "code" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "accessToken" TEXT NOT NULL,
    "username" VARCHAR(39) NOT NULL,
    "type" "enum_User_type" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User.accessToken_unique" ON "User"("accessToken");

-- CreateIndex
CREATE UNIQUE INDEX "User.username_unique" ON "User"("username");

-- AddForeignKey
ALTER TABLE "Snippet" ADD FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
