version: '3'
services:
  devcontainer:
    image: node:16
    volumes:
      - ..:/workspace:cached
    env_file:
      - ../.env.local
      - ../src/prisma/.env.local
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:13.3-alpine
    env_file:
      - ../src/prisma/.env.local
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  data: