name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:16
    services:
      db:
        image: postgres:13.3-alpine
      env:
        POSTGRES_PASSWORD: postgres
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: generate types
        run: npm run type:gen

      - name: type check
        run: npm run type:check

      - name: lint
        run: npm run lint

      - name: migrate and seed database
        run: npx prisma migrate deploy && npx prisma db seed --preview-feature

      - name: test
        run: npm test
